### ISSUE TITLE
某些系统应用检测不到，无法生成图标

### ISSUE THREAD

**Issue by SteveChern** [oxoooo/materialize#4]
例如"镜子"，huawei G621-TL00

**Comment by xingrz** [comment]
如果可能，请提供"镜子"的APK。

**Comment by SteveChern** [comment]
http://pan.baidu.com/s/1qW1SUq4
apk附件发送失败，已上传至百度云，请自行下载。

oucstevechen@gmail.com

发件人： XiNGRZ
发送时间： 2015-11-29 21:23
收件人： oxoooo/materialize
抄送： CheSteven
主题： Re: [materialize] 某些系统应用检测不到，无法生成图标 (#4)
如果可能，请提供"镜子"的APK。

**Comment by xingrz** [comment]
好吧，懂了。华为镜子的包名是 `com.android.hwmirror`，而一般的非 Android 系统应用是不会使用 `com.android` 这个前缀的，所以被我过滤了。

我会考虑加上是否过滤系统应用的开关。
